Feat: 외부 API 저장 기능 구현
nhnacademy-be7-55G-COM/55G.COM-bookApi pull request #3
Opened 2024-10-28 00:15 UTC by Gyubin-Han

#1 #2 외부 API(알라딘)에서 초기에 사용할 데이터를 불러와 저장하는 기능 구현

2024-10-28 01:26 UTC, Jung-won-seok approved these changes

2024-10-28 01:29 UTC, desworld approved these changes
수고하셨습니다

2024-10-28 01:45 UTC, FlowerfulFort requested changes
수정사항 몇몇 있습니다

2024-10-28 01:45 UTC, FlowerfulFort commented on src/main/java/shop/S5G/bookApi/runner/InitBookApiApplicationRunner.java
> +            Optional<Author> authorOptional = authorRepository.findByName(authorName);
name은 unique 필드가 아닙니다. 동명이인에 대한 대책이 있어야 하거나 id로 조회해야 할 것입니다.

2024-10-28 01:45 UTC, FlowerfulFort commented on src/main/java/shop/S5G/bookApi/runner/InitBookApiApplicationRunner.java
> +        Optional<Publisher> publisherOptional = publisherRepository.findByPublisherName(
name은 unique 필드가 아닙니다.

2024-10-28 01:45 UTC, FlowerfulFort commented on src/main/java/shop/S5G/bookApi/entity/Book.java
> +    @ManyToOne
lazy fetch를 고려해보세요

2024-10-28 01:45 UTC, FlowerfulFort commented on src/main/java/shop/S5G/bookApi/entity/Publisher.java
> +@Builder
`@Builder`를 막 붙이시지는 마시고 인자가 작으면 생성자를 만드시는게 낫습니다.

2024-10-28 01:45 UTC, FlowerfulFort commented on pom.xml
> +		<dependency>
spring-boot-starter-validation으로 바꾸는게 나을것같습니다

2024-10-28 02:07 UTC, Gyubin-Han commented on src/main/java/shop/S5G/bookApi/runner/InitBookApiApplicationRunner.java
> +            Optional<Author> authorOptional = authorRepository.findByName(authorName);
사실 이름과 같이 동명이인 등 unique하지 않은 데이터들을 어떻게 처리해야 할 지 많이 고민하게 되었는데요. 그런데 방법이 떠오르지 않아 우선 이름을 기준으로 검색하는 방향으로 구현하게 되었습니다. 혹시 별도의 구분 방법이 있을지요?

알라딘으로부터 받아오는 API 응답 데이터는 아래와 같습니다.
``` json
{
      "title": "조재선의 글스토랑 - 가족이라 쓰고 행복이라 읽는다",
      "link": "http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=350393285&amp;partner=openAPI&amp;start=api",
      "author": "조재선 (지은이), 장지혜 (그림)",
      "pubDate": "2024-10-15",
      "description": "",
      "isbn": "K142934989",
      "isbn13": "9791193607602",
      "itemId": 350393285,
      "priceSales": 18000,
      "priceStandard": 20000,
      "mallType": "BOOK",
      "stockStatus": "",
      "mileage": 1000,
      "cover": "https://image.aladin.co.kr/product/35039/32/coversum/k142934989_1.jpg",
      "categoryId": 51371,
      "categoryName": "국내도서>에세이>한국에세이",
      "publisher": "행복에너지",
      "salesPoint": 0,
      "adult": false,
      "fixedPrice": true,
      "customerReviewRank": 0,
      "subInfo": {}
}
```

2024-11-08 05:46 UTC, FlowerfulFort approved these changes

2024-11-08 05:47 UTC, merged